title: Proyecto algebra lineal
description: Proyecto en matlab de algebra lineal
template:
  repo: proyecto-algebra-lineal-template
  name: proyecto-algebra-lineal
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
